# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8_WbRdlAvgGPmfwt9ieDEaGs8EvmC0W
"""

import pandas as pd
import numpy as np

# Creating sample Mall Customer dataset
data = {
    'CustomerID': range(1, 21),
    'Gender': ['Male','Female','Female','Female','Female','Female','Female','Female','Male','Female',
               'Male','Female','Female','Female','Male','Male','Female','Male','Male','Female'],
    'Age': [19,21,20,23,31,22,35,23,64,30,67,35,58,24,37,22,35,20,52,35],
    'Annual_Income_k': [15,15,16,16,17,17,18,18,19,19,20,20,21,21,23,23,24,24,25,25],
    'Spending_Score': [39,81,6,77,40,76,6,94,3,72,14,99,15,77,13,79,35,66,29,98]
}

df = pd.DataFrame(data)
df.head()